### ISSUE TITLE
Fix the marble diagrams

### ISSUE THREAD

**Issue by aerabi** [rxjsx/rxjsx#5]
The marble diagrams were imported from the [`rxjs-pipe-ext`](https://github.com/aerabi/rxjs-pipe-ext) repo and had initially some name inaccuracies that were [fixed on the source repo](https://github.com/aerabi/rxjs-pipe-ext/issues/16). The same fix should be applied to this repo as well.

**Comment by ManishS6** [comment]
@aerabi I would like to work on this,
Kindly assign me this task.

**Comment by aerabi** [comment]
It's all yours, @ManishS6. Best of luck.

**Comment by ManishS6** [comment]
@aerabi I have completed the task.

**Comment by aerabi** [comment]
Nicely done. You could also be interested in this one: #7.
