### ISSUE TITLE
Convert the fixed SVG diagrams into PNG and add them to the README

### ISSUE THREAD

**Issue by aerabi** [rxjsx/rxjsx#7]
In the context of #6, we can now convert the SVG diagrams into their PNG versions and add them into the [operators' README](https://github.com/rxjsx/rxjsx/blob/master/docs/operators/README.md).

**Comment by inomag** [comment]
Hi @aerabi , Can I work on this issue?

**Comment by ManishS6** [comment]
@aerabi As offered by you in #5 I would love to contribute to this as well.

**Comment by aerabi** [comment]
> Hi @aerabi , Can I work on this issue?

All the best. :rocket:

**Comment by aerabi** [comment]
> @aerabi As offered by you in #5 I would love to contribute to this as well.

I appreciate your enthusiasm @ManishS6. Let's leave this issue to @inomag, as he volunteered first, and you can do #8 which is a related to the one you fixed earlier.

**Comment by ManishS6** [comment]
> > @aerabi As offered by you in #5 I would love to contribute to this as well.
> 
> I appreciate your enthusiasm @ManishS6. Let's leave this issue to @inomag, as he volunteered first, and you can do #8 which is related to the one you fixed earlier.

Sure, on it.
